### ISSUE TITLE
software

### ISSUE THREAD

**Issue by lianzaozi** [fab-machines/LaserDuo#1]
What kind of software is used to control the laser cutting machine?

**Comment by satshas** [comment]
Hello @lianzaozi,

the following software is used:

- grbl, https://github.com/gnea/grbl,  on the satshakit-grbl
- UGSG Platform, https://winder.github.io/ugs_website/guide/platform/, to operate the machine
-  Visicut,, https://winder.github.io/ugs_website/guide/platform/, to generate the GCode (use grbl driver)

let me know if you need more information
